/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package pl.rcebula.analysis.math_log_parser.javacc;

public interface ParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTEXPR = 1;
  public int JJTTERM = 2;
  public int JJTPRIM = 3;


  public String[] jjtNodeName = {
    "START",
    "EXPR",
    "TERM",
    "PRIM",
  };
}
/* JavaCC - OriginalChecksum=9d7a0449ac3828b6e7d4fef92207f2da (do not edit this line) */
