/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package pl.rcebula.analysis.math_log_parser.javacc;

public interface ParserTreeConstants
{
  public int JJTEXPR = 0;
  public int JJTEXPR_1 = 1;
  public int JJTTERM = 2;
  public int JJTTERM_1 = 3;
  public int JJTFACT = 4;
  public int JJTFACT_1 = 5;
  public int JJTPRIM = 6;


  public String[] jjtNodeName = {
    "EXPR",
    "EXPR_1",
    "TERM",
    "TERM_1",
    "FACT",
    "FACT_1",
    "PRIM",
  };
}
/* JavaCC - OriginalChecksum=c095e109945baae16c72d8a330743c47 (do not edit this line) */
