/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package pl.rcebula.analysis.math_log_parser.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int TIMES = 7;
  /** RegularExpression Id. */
  int DIVIDE = 8;
  /** RegularExpression Id. */
  int POWER = 9;
  /** RegularExpression Id. */
  int OPEN_PAR = 10;
  /** RegularExpression Id. */
  int CLOSE_PAR = 11;
  /** RegularExpression Id. */
  int KEYWORDS = 12;
  /** RegularExpression Id. */
  int NONE = 13;
  /** RegularExpression Id. */
  int TRUE = 14;
  /** RegularExpression Id. */
  int FALSE = 15;
  /** RegularExpression Id. */
  int INT = 16;
  /** RegularExpression Id. */
  int FLOAT = 17;
  /** RegularExpression Id. */
  int DOT = 18;
  /** RegularExpression Id. */
  int DIGIT_NON_ZERO = 19;
  /** RegularExpression Id. */
  int DIGIT = 20;
  /** RegularExpression Id. */
  int ID_STRUCT = 21;
  /** RegularExpression Id. */
  int ID = 22;
  /** RegularExpression Id. */
  int UNDERLINE = 23;
  /** RegularExpression Id. */
  int UTF_LETTER = 24;
  /** RegularExpression Id. */
  int STRING = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\t\"",
    "\" \"",
    "<token of kind 4>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"(\"",
    "\")\"",
    "<KEYWORDS>",
    "<NONE>",
    "<TRUE>",
    "<FALSE>",
    "<INT>",
    "<FLOAT>",
    "\".\"",
    "<DIGIT_NON_ZERO>",
    "<DIGIT>",
    "<ID_STRUCT>",
    "<ID>",
    "<UNDERLINE>",
    "<UTF_LETTER>",
    "<STRING>",
  };

}
