/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package pl.rcebula.analysis.math_log_parser.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OR = 5;
  /** RegularExpression Id. */
  int AND = 6;
  /** RegularExpression Id. */
  int EQ = 7;
  /** RegularExpression Id. */
  int NEQ = 8;
  /** RegularExpression Id. */
  int LS = 9;
  /** RegularExpression Id. */
  int LE = 10;
  /** RegularExpression Id. */
  int GT = 11;
  /** RegularExpression Id. */
  int GE = 12;
  /** RegularExpression Id. */
  int PLUS = 13;
  /** RegularExpression Id. */
  int MINUS = 14;
  /** RegularExpression Id. */
  int TIMES = 15;
  /** RegularExpression Id. */
  int DIVIDE = 16;
  /** RegularExpression Id. */
  int MODULO = 17;
  /** RegularExpression Id. */
  int POWER = 18;
  /** RegularExpression Id. */
  int EXCL_MARK = 19;
  /** RegularExpression Id. */
  int COMMA = 20;
  /** RegularExpression Id. */
  int DOLLAR = 21;
  /** RegularExpression Id. */
  int OPEN_INDX = 22;
  /** RegularExpression Id. */
  int CLOSE_INDX = 23;
  /** RegularExpression Id. */
  int OPEN_PAR = 24;
  /** RegularExpression Id. */
  int CLOSE_PAR = 25;
  /** RegularExpression Id. */
  int KEYWORDS = 26;
  /** RegularExpression Id. */
  int NONE = 27;
  /** RegularExpression Id. */
  int TRUE = 28;
  /** RegularExpression Id. */
  int FALSE = 29;
  /** RegularExpression Id. */
  int INT = 30;
  /** RegularExpression Id. */
  int FLOAT = 31;
  /** RegularExpression Id. */
  int DOT = 32;
  /** RegularExpression Id. */
  int DIGIT_NON_ZERO = 33;
  /** RegularExpression Id. */
  int DIGIT = 34;
  /** RegularExpression Id. */
  int ID_STRUCT = 35;
  /** RegularExpression Id. */
  int ID = 36;
  /** RegularExpression Id. */
  int SIMPLE_ID = 37;
  /** RegularExpression Id. */
  int UNDERLINE = 38;
  /** RegularExpression Id. */
  int UTF_LETTER = 39;
  /** RegularExpression Id. */
  int STRING = 40;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\t\"",
    "\" \"",
    "<token of kind 4>",
    "\"||\"",
    "\"&&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"^\"",
    "\"!\"",
    "\",\"",
    "\"$\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "<KEYWORDS>",
    "<NONE>",
    "<TRUE>",
    "<FALSE>",
    "<INT>",
    "<FLOAT>",
    "\".\"",
    "<DIGIT_NON_ZERO>",
    "<DIGIT>",
    "<ID_STRUCT>",
    "<ID>",
    "<SIMPLE_ID>",
    "<UNDERLINE>",
    "<UTF_LETTER>",
    "<STRING>",
  };

}
