/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package pl.rcebula.analysis.math_log_parser.javacc;

public interface ParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTEXPR = 1;
  public int JJTOR_EX = 2;
  public int JJTOR_EX_1 = 3;
  public int JJTAND_EX = 4;
  public int JJTAND_EX_1 = 5;
  public int JJTEQ_EX = 6;
  public int JJTEQ_EX_1 = 7;
  public int JJTCMP_EX = 8;
  public int JJTCMP_EX_1 = 9;
  public int JJTADD_EX = 10;
  public int JJTADD_EX_1 = 11;
  public int JJTMUL_EX = 12;
  public int JJTMUL_EX_1 = 13;
  public int JJTPOW_EX = 14;
  public int JJTPOW_EX_1 = 15;
  public int JJTNEG_EX = 16;
  public int JJTINDX_EX = 17;
  public int JJTINDX_EX_1 = 18;
  public int JJTPRIM = 19;


  public String[] jjtNodeName = {
    "START",
    "EXPR",
    "OR_EX",
    "OR_EX_1",
    "AND_EX",
    "AND_EX_1",
    "EQ_EX",
    "EQ_EX_1",
    "CMP_EX",
    "CMP_EX_1",
    "ADD_EX",
    "ADD_EX_1",
    "MUL_EX",
    "MUL_EX_1",
    "POW_EX",
    "POW_EX_1",
    "NEG_EX",
    "INDX_EX",
    "INDX_EX_1",
    "PRIM",
  };
}
/* JavaCC - OriginalChecksum=ed7589c61abf1cefd9b55b001b251fa3 (do not edit this line) */
